### ISSUE TITLE
Default handler mapping is unusable

### ISSUE THREAD

**Issue by mtojek** [docker/go-healthcheck#2]
Hi,

In the code snippet, I've quoted below, you are registering a default mapping "/debug/health" for the DefaultServerMux:

```
// Registers global /debug/health api endpoint, creates default registry
func init() {
    DefaultRegistry = NewRegistry()
    http.HandleFunc("/debug/health", StatusHandler)
}
```

Actually, it makes the healthcheck projects unusable (even hackable) with non-standard HTTP server usages. Imagine than I may be want to publish the /debug/health endpoint for my internal HTTP server, not the production one (yup, the app starts two webservers). That's the first issue.

Secondly, you've hardcoded the "/debug/health" mapping which also implies additional adjustments in client projects (f. e. "/debug/health" doesn't suit me at all ;). 

In fact I can patch the DefaultServeMux after importing, but that's hacking the import lifecycle not a clean design.

Please rethink using the function init, registering endpoint for DefaultServeMux and hardcoding the handler mapping.

**Comment by stevvooe** [comment]
@mtojek This is the exact pattern used in the standard library for `/debug/*` packages. https://golang.org/src/net/http/pprof/pprof.go#L66 is an example.

You can mount the health endpoint any where you want with the exported `StatusHandler` symbol.

We do everything you're describing and more.

You're problem is using the default serve mux as your "production" server. Because routes are implicitly registered using standard packages, using the default serve mux can be a bit of a liability.
